run:
  timeout: 1m

linters-settings:
  goimports:
    local-prefixes: github.com/nikhil-prabhu/clouddetect

  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
